### ISSUE TITLE
Support to running oldest versions of PHPUnit?

### ISSUE THREAD

**Issue by cauealvesbraz** [php-actions/phpunit#15]
Hey, congrats for this action.

Do you have any idea for support the oldest versions of PHPUnit? Like 5, 6 and 7?

**Comment by g105b** [comment]
Cheers. Every past version introduces extra maintenance, so I decided to just support the latest and previous releases, as I thought people using Github Actions would be more likely to be using current builds.

That being said, I have recently changed the version release strategy to match PHPUnit's (so the action v8 ships with PHPUnit v8, for example), so this should be much easier to maintain.

If there is demand for other versions, I'll do what I can to support them. Are you requesting all three prior versions 5, 6 and 7, or is your question more of a curiosity?

**Comment by cauealvesbraz** [comment]
Hello Greg, thanks for details and I understand your decision.

I'm requesting the version 5. Because I need to kept the maintenance of packages and projects that's running with php@5.6

**Comment by g105b** [comment]
I feel your pain, we've all been there. Not ideal, but realistic.

I will try and get the other versions supported. I hope to not take too long. Watch this space.

**Comment by g105b** [comment]
Hi @cauealvesbraz 

I've made back-released branches including v5, v6 and v7. I hope this works for you.

Use them by stating `uses: php-actions/phpunit@v5` in your action.yml. I've made some tests to prove it works in the [PHPUnit example repository](https://github.com/php-actions/phpunit). Check out the branches for each version.

Cheers!

**Comment by cauealvesbraz** [comment]
Hey @g105b,

I'm appreciated with your focus for make this supports, congrats. 

Thank you!

**Comment by g105b** [comment]
[You're welcome!](https://github.com/sponsors/g105b/)
