### ISSUE TITLE
Remove default bootstrap value

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [php-actions/phpunit#18]
Is it possible to change this so that when no `bootstrap:` config is provided, no default value is used and `--bootstrap` is omitted? My bootstrap file is specified in *phpunit.xml.dist* already.

**Comment by g105b** [comment]
Hi @PanCakeConnaisseur ,

I've checked the PHPUnit docs and there shouldn't be a default value for this option, so I will remove its default value in the next update, and will close this issue when it's done.

Cheers,
Greg.

**Comment by g105b** [comment]
The default value has been dropped, and I am about to make a release to bring this change to the v7, v8 and v9 tags.
