### ISSUE TITLE
the requested PHP extension dom is missing from your system

### ISSUE THREAD

**Issue by lablnet** [php-actions/phpunit#19]
This does not seems to work properly 

`the requested PHP extension dom is missing from your system`

https://github.com/zestframework/Zest_Framework/pull/314/checks?check_run_id=1350645786

**Comment by g105b** [comment]
Thanks for your issue report. This is a duplicate of #17 and I'm currently working on it. More info in that thread.

**Comment by g105b** [comment]
https://github.com/php-actions/phpunit/issues/16#issuecomment-724061958

> Woo! Finally, I have a working solution. Sorry it's taken so long, but I've had to have been doing this alongside paid work.
> 
> I've got a system that allows PHP, PHPUnit and Composer to have their versions and arguments managed purely from the action's yaml configuration. I'll merge things and make a release on all the actions later today after updating the readmes.

**Comment by g105b** [comment]
Take a look here: https://github.com/php-actions/example-phpunit/blob/master/composer.json#L8

This is an example project that runs PHPUnit tests, but as part of my work for these issues, I've added a few extensions (including DOM) as requirements to the composer.json. You can see the passing action here: https://github.com/php-actions/example-phpunit/actions/runs/354003732

I've just got to wrap this up into their relevant releases and we're good to go - your Zest Framework issue should be resolved.

**Comment by lablnet** [comment]
Thanks yes it solves the issue .

**Comment by g105b** [comment]
Great! Have a nice day, stay productive.
