### ISSUE TITLE
Use an array to process arguments

### ISSUE THREAD

**Issue by g105b** [php-actions/phpunit#23]
According to [SC2089](https://github.com/koalaman/shellcheck/wiki/SC2089), quotes around arguments mean they are treated "literally".

The problem occurs because I consider quotes to be important for file names. If the file name has a space in it, it should be treated "literally" as far as I understand.

But I'm aware that I don't have the best understanding of bash scripts, and the problem is removed when  the quotes are removed... but this means that certain characters won't be allowed in file names.

On this line, I've removed the quote around the filename: https://github.com/php-actions/phpunit/blob/76f35f77b0b6e2ca779cb95e0790c307d59f68c3/phpunit-action.bash#L20

On the next argument, the quotes still exist, so I assume this will cause an issue if this argument is used: https://github.com/php-actions/phpunit/blob/76f35f77b0b6e2ca779cb95e0790c307d59f68c3/phpunit-action.bash#L25

Please can somebody with a little more bash experience than me take a look at this? Thanks!

**Comment by zklosko** [comment]
To my knowledge, because $ACTION_LOG_JUNIT is stored as a string, it should remain a string when passed in as $ACTION_LOG_JUNIT, no extra quotes needed.

**Comment by g105b** [comment]
Thanks, @zklosko .

This is now implemented in master. Each argument is pushed to the array before it is used: https://github.com/php-actions/phpunit/blob/master/phpunit-action.bash#L20

Any issues with any of the arguments, please let me know here.
