### ISSUE TITLE
add support for xml and clover output

### ISSUE THREAD

**Issue by mimmi20** [php-actions/phpunit#33]
It would be helpful if this action would support the PHPUnits CLI Parameters "--coverage-clover" and "--coverage-xml".

**Comment by g105b** [comment]
Hi @mimmi20 

Thank you for opening this. You should be able to pass any arguments to the script, but I'll look into this and provide an example at https://GitHub.com/php-actions/example-phpunit

I'm away this weekend but will pick up next week.

Greg.
