### ISSUE TITLE
repository not found: name unknown: docker package does not exist under owner

### ISSUE THREAD

**Issue by netdjw** [php-actions/phpunit#38]
I have this workflow yml file:

```yml
name: PR automatic code review - Laravel
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_version: 8
        working_dir: laravel/
    - uses: php-actions/phpunit@v3
      with:
        php_version: 8
        bootstrap: laravel/vendor/autoload.php
        configuration: laravel/phpunit.xml
        memory_limit: 256M
```

When I try to use this GitHub action I get this error message:

```
Login Succeeded
Pulling docker.pkg.github.com/myuser/myrepo/php-actions_phpunit_myrepo:php-8-build2
Error response from daemon: repository docker.pkg.github.com/myuser/myrepo/php-actions_phpunit_myrepo 
    not found: name unknown: docker package "php-actions_phpunit_myrepo" does not exist under owner "myuser/myrepo"
Dockerfile:
FROM php:8-cli-alpine
RUN apk add --update --no-cache zip git bash openssh
error checking context: 'can't stat '/home/runner/work/myrepo/myrepo/laravel/storage/framework/testing/disks''.
```

Any idea how can I fix this?

**Comment by g105b** [comment]
Will check this out in the morning.

**Comment by netdjw** [comment]
@g105b do you have any progress on this issue?

**Comment by Eboubaker** [comment]
I think the repo must be public?, how to pass a token to the build workflow?.

**Comment by netdjw** [comment]
@g105b the repo is not public, but now everything works fine. I didn't modify anything, so I thing there was a version mismatch or something.

**Comment by g105b** [comment]
OK Thanks for letting me know. Sorry for my quietness - work has really been busy recently.

I've noticed a few issues with Github Actions' Packages recently, and I'm hoping that https://github.com/php-actions/php-build/pull/8 will resolve a lot of these for php-actions repositories.
