### ISSUE TITLE
Option to specify Bootstrap file location

### ISSUE THREAD

**Issue by pres** [php-actions/phpunit#5]
I can't used this action, as it always looks for the bootstrap file in `vendor/autoload.php`, however my bootstraop/autoload.php file is at an other location.

I tried to fix it and make bootstrap an argument and created a pull request for it, #4.

Could you verify, merge and release a new version?
Thanks!

**Comment by g105b** [comment]
Closed by #4

**Comment by g105b** [comment]
I would appreciate your views on the release strategy for this action. Currently php-actions/phpunit@v1 will not receive this merged PR, but as I haven't pushed past v1 yet with Github actions, I'm not sure what the best versioning strategy is.

Feedback is appreciated, my current idea is to use the semantic versioning to release v1.1.0, but I think that would require changes to your action config to `use php-actions/phpunit@v1.1.0`.

**Comment by pres** [comment]
Thank you for merging it. I think releasing it as v1.1.0 is the best. 
If someone wants to use the new feature and specify an own path to his bootstrap file, he needs to update his action nonetheless.

**Comment by g105b** [comment]
Indeed. In the meantime, you can use php-actions/phpunit@master - I will see what other CLI arguments need passing over, and provide that functionality in the next release too.
